# This is a config for E2B sandbox template.
# You can use template ID (6bta0b86cu7cj3ef28g7) or template name (v0-nextjs-jan22) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("v0-nextjs-jan22") # Sync sandbox
# sandbox = await AsyncSandbox.create("v0-nextjs-jan22") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('v0-nextjs-jan22')

team_id = "cd70c291-84f4-4e78-9332-0831b1f30711"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "v0-nextjs-jan22"
template_id = "6bta0b86cu7cj3ef28g7"
